###
# @name create-user
POST http://localhost:3333/user
content-type: application/json

{
    "email": "felipea@gmail.com",
    "password": "12345678",
    "name": "felipe"
}

###
# @name delete-user
DELETE http://localhost:3333/user/[idUser]

###
# @name authenticate
POST http://localhost:3333/login
content-type: application/json

{
    "email": "felipe.de@gmail.com",
    "password": "12345678"
}

###
# @name validate
POST http://localhost:3333/validate
Content-Type: application/json

{
    "token": "[token]"
}

###
# @name create-task
POST http://localhost:3333/task
Content-Type: application/json
Authorization: Bearer [token]


{
    "title": "Nadar na piscina",
    "description": "nadar para relaxar e treinar para o triato"
}

###
# @name get-all-tasks
GET  http://localhost:3333/task
Authorization: Bearer [token]

###
# @name update-task
PUT   http://localhost:3333/task/311dd030-3c03-4465-92ab-af384dd05f08
Content-Type: application/json
Authorization: Bearer [token]


{
    "title": "Integrar o back no front",
    "description": "é de estrema necessidade fazer isso"
}

###
# @name toggle-task
PATCH   http://localhost:3333/task/toggle-checked/[idTask]
Content-Type: application/json
Authorization: Bearer [token]

###
# @name delete-task
DELETE    http://localhost:3333/task/[idTask]
Content-Type: application/json
Authorization: Bearer [token]
